/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Licorice_GLTF.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Plant_model/Licorice_GLTF.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node_#0'].geometry} material={nodes['Node_#0'].material} />
    </group>
  )
}

useGLTF.preload('/Plant_model/Licorice_GLTF.gltf')
