/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 plant.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/plant.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Group4.geometry} material={materials['Mud_Mound.001']} position={[11.204, 2.172, -31.773]} rotation={[0, 0, Math.PI]} scale={2.782} />
    </group>
  )
}

useGLTF.preload('/plant.gltf')
